# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Your awesome title
email: hello@joannajia.com
description: > # this means to ignore newlines until "baseurl:"
  Everything I've been up to lately.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://joannajia.com" # the base hostname & protocol for your site
linkedin_username: jjia25
github_username:  jjia25

# Build settings
markdown: kramdown

theme: jekyll-theme-merlot
